LinkDev.IKEA.PL/Controllers/DepartmentController.cs
using AutoMapper;
using LinkDev.IKEA.BLL.Models.Departments;
using LinkDev.IKEA.BLL.Services.Departments;
using LinkDev.IKEA.PL.ViewModels.Departments;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LinkDev.IKEA.PL.Controllers
{
	/// Inheritance: DepartmentController is  a Controller
	/// Composition: DepartmentController has a IDepartmentService

	[Authorize]
	public class DepartmentController : Controller
    {
        #region Services [Dependency Injection]

        private readonly IDepartmentService _departmentService;
        private readonly IMapper _mapper;
        private readonly ILogger<DepartmentController> _logger;
        private readonly IWebHostEnvironment _environment;
        public DepartmentController(IDepartmentService departmentService, IMapper mapper, ILogger<DepartmentController> logger, IWebHostEnvironment environment)
        {
            _departmentService = departmentService;
            _mapper = mapper;
            _logger = logger;
            _environment = environment;
        }

        #endregion

        #region Index

        [HttpGet] // GET: /Department/Index
        public async Task<IActionResult> Index()
        {
            // View's Dictionary: Pass Data from Controller[Action] to View (from View -> [PartialView, Layout])

            /// 1. ViewData is a Dictionary Type Property (Introduced in ASP.NET Framework 3.5)
            ///    => It helps us to transfer the data from the controller[Action] to View

             ViewData["Obj"] = "Hello ViewData";

            /// 2. ViewBag is a Dynamic Type Property (Introduced in ASP.NET Framework 4.0 based on dynamic Feature)
            ///    => It helps us to transfer the data from the controller[Action] to View

            ViewBag.Obj = "Hello ViewBag";
            // ViewBag.Obj = new { Id = 10, Name = "Ahmed"};

            var departments = await _departmentService.GetAllDepartmentsAsync();
            return View(departments);
        }

        #endregion

        #region Details 

        [HttpGet] // /Department/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
                return BadRequest();

            var department = await _departmentService.GetDepartmentByIdAsync(id.Value);
            if (department is null)
                return NotFound();

            return View(department);
        } 

        #endregion

        #region Create

        [HttpGet] // GET: /Department/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // POST
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DepartmentViewModel departmentVM)
        {
            if (!ModelState.IsValid)            // Server-Side Validation
                return View(departmentVM);

            string message = string.Empty;
            try
            {
                // Manual Mapping
                /// var createdDepartment = new CreatedDepartmentDto()
                /// {
                ///     Name = departmentVM.Name,
                ///     Code = departmentVM.Code,
                ///     Description = departmentVM.Description,
                ///     CreationDate = departmentVM.CreationDate,
                /// };

                var createdDepartment = _mapper.Map<CreatedDepartmentDto>(departmentVM);
                var created = await _departmentService.CreateDepartmentAsync(createdDepartment) > 0;

                // 3. TempData: is a property of Type Dictionary Object (introduced in ASP.NET Framework 3.5)
                //            : used for transfering the data between 2 consuctive Requests

                if (created)
                    message = "Department has been Created Successfully";
                else
                    message = "Department is not Created";

                TempData["Message"] = message;
                return RedirectToAction(nameof(Index));
                

            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);

                // 2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "an error has occured during creating the department :(";

                TempData["Message"] = message;

            }

            ModelState.AddModelError(string.Empty, message);
            return View(departmentVM);

        }

        #endregion

        #region Update

        [HttpGet]   // Department/Edit/id?
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return BadRequest();    // 400

            var department = await _departmentService.GetDepartmentByIdAsync(id.Value);

            if (department is null)
                return NotFound();      // 404

            var departmentVM = _mapper.Map<DepartmentDetailsDto, DepartmentViewModel>(department);

            return View(departmentVM);
        }

        [HttpPost]   // POST
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, DepartmentViewModel department)
        {
            if (!ModelState.IsValid)           // Server-Side Validation
                return View(department);

            var message = string.Empty;

            try
            {
                // Manual Mapping
                var departmentToUpdate = new UpdatedDepartmentDto()
                {
                    Id = id,
                    Name = department.Name,
                    Code = department.Code,
                    Description = department.Description,
                    CreationDate = department.CreationDate,
                };

                //var departmentToUpdate = _mapper.Map<UpdatedDepartmentDto>(department);

                var updated = await _departmentService.UpdateDepartmentAsync(departmentToUpdate) > 0;

                if (updated)
                        message = "Department has been Updated Successfully";
                    else
                        message = "Department is not Updated";

                TempData["Message"] = message;
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);

                // 2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "an error has occured during updating the department :(";
            }

            ModelState.AddModelError(string.Empty, message);
            return View(department);
        }

        #endregion

        #region Delete

        [HttpGet]   // Department/Delete/id?
        public IActionResult Delete(int? id)
        {
            if (id is null)
                return BadRequest();

            var department = _departmentService.GetDepartmentByIdAsync(id.Value);

            if (department is null)
                return NotFound();

            return View(department);
        }

        [HttpPost]  // POST
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var message = string.Empty;

            try
            {
                var deleted = await _departmentService.DeleteDepartmentAsync(id);

                if (deleted)
                    return RedirectToAction(nameof(Index));

                message = "an error has occured during deleting the department :(";
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);

                // 2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "an error has occured during deleting the department :(";
            }

            //ModelState.AddModelError(string.Empty, message);
            return RedirectToAction(nameof(Index));
        } 

        #endregion
    }
}

LinkDev.IKEA.PL/Controllers/EmployeeController.cs
using AutoMapper;
using LinkDev.IKEA.BLL.Models.Departments;
using LinkDev.IKEA.BLL.Models.Employees;
using LinkDev.IKEA.BLL.Services.Departments;
using LinkDev.IKEA.BLL.Services.Employees;
using LinkDev.IKEA.DAL.Entities.Departments;
using LinkDev.IKEA.DAL.Entities.Employees;
using LinkDev.IKEA.PL.ViewModels.Departments;
using LinkDev.IKEA.PL.ViewModels.Employees;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LinkDev.IKEA.PL.Controllers
{
	[Authorize]
	public class EmployeeController : Controller
    {
        #region Services [Dependency Injection]

        private readonly IEmployeeService _employeeService;
        private readonly IDepartmentService? _departmentService;
        private readonly ILogger<EmployeeController> _logger;
        private readonly IWebHostEnvironment _environment;
        private readonly IMapper _mapper;

        public EmployeeController(
            IEmployeeService employeeService, 
            ILogger<EmployeeController> logger, 
            IWebHostEnvironment environment,
            IMapper mapper
            )
        {
            _employeeService = employeeService;
            _logger = logger;
            _environment = environment;
            _mapper = mapper;
        }

        #endregion

        #region Index

        [HttpGet] // GET: /Employee/Index
        public async Task<IActionResult> Index(string search)
        {
            var employees = await _employeeService.GetEmployeesAsync(search);

            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                return PartialView("Partials/_EmployeeListPartial", employees);

            return View(employees);
        }

        #endregion

        #region Details 

        [HttpGet] // /Employee/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null)
                return BadRequest();

            var employee = await _employeeService.GetEmployeeByIdAsync(id.Value);
            if (employee is null)
                return NotFound();

            return View(employee);
        }

        #endregion

        #region Create

        [HttpGet] // GET: /Employee/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // POST
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            if (!ModelState.IsValid)            // Server-Side Validation
                return View(employeeVM);

            string message = string.Empty;
            try
            {
                // Manual Mapping
                /// var createdEmployee = new CreatedEmployeeDto()
                /// {
                ///     Name = employeeVM.Name,
                ///     Age = employeeVM.Age,
                ///     Address = employeeVM.Address,
                ///     Salary = employeeVM.Salary,
                ///     IsActive = employeeVM.IsActive,
                ///     Email = employeeVM.Email,
                ///     PhoneNumber = employeeVM.PhoneNumber,
                ///     HiringDate = employeeVM.HiringDate,
                ///     Gender = employeeVM.Gender,
                ///     EmployeeType = employeeVM.EmployeeType,
                ///     DepartmentId = employeeVM.DepartmentId,
                ///     Image = employeeVM.Image,
                /// };

                var createdEmployee = _mapper.Map<CreatedEmployeeDto>(employeeVM);

                var result = await _employeeService.CreateEmployeeAsync(createdEmployee);
                if (result > 0)
                    message = "Employee has been Created Successfully.";                  
                else
                    message = "Failed to create employee.";

                TempData["Message"] = message;
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);

                // 2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "an error has occured during creating the Employee :(";

            }

            ModelState.AddModelError(string.Empty, message);
            return View(employeeVM);
        }

        #endregion

        #region Update

        [HttpGet]   // Employee/Edit/id?
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return BadRequest();    // 400
        
            var employee = await _employeeService.GetEmployeeByIdAsync(id.Value);
        
            if (employee is null)
                return NotFound();      // 404

            // Manual Mapping 
            /// var departmentVM new EmployeeViewModel()
            /// {
            ///     Name = employee.Name,
            ///     Address = employee.Address,
            ///     Email = employee.Email,
            ///     Age = employee.Age,
            ///     Salary = employee.Salary,
            ///     PhoneNumber = employee.PhoneNumber,
            ///     IsActive = employee.IsActive,
            ///     EmployeeType = employee.EmployeeType,
            ///     Gender = employee.Gender,
            ///     HiringDate = employee.HiringDate,
            ///     DepartmentId = employee.DepartmentId,
            /// };
            
            var employeeVM = _mapper.Map<EmployeeDetailsDto, EmployeeViewModel>(employee);

            return View(employeeVM);
        }
        
        [HttpPost]   // POST
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            if (!ModelState.IsValid)           // Server-Side Validation
                return View(employeeVM);
        
            var message = string.Empty;
        
            try
            {
                // Manual Mapping
                /// var employeeToUpdate = new UpdatedEmployeeDto()
                /// {
                ///     Id = id,
                ///     Name = employeeVM.Name,
                ///     Age = employeeVM.Age,
                ///     Address = employeeVM.Address,
                ///     Salary = employeeVM.Salary,
                ///     IsActive = employeeVM.IsActive,
                ///     Email = employeeVM.Email,
                ///     PhoneNumber = employeeVM.PhoneNumber,
                ///     HiringDate = employeeVM.HiringDate,
                ///     Gender = employeeVM.Gender,
                ///     EmployeeType = employeeVM.EmployeeType,
                ///     DepartmentId = employeeVM.DepartmentId,
                /// };

                var employeeToUpdate = _mapper.Map<UpdatedEmployeeDto>(employeeVM);

                employeeToUpdate.Id = id;

                var updated = await _employeeService.UpdateEmployeeAsync(employeeToUpdate) > 0;

                if (updated)
                    message = "Employee has been Updated Successfully";
                else
                    message = "Failed to update employee.";

                TempData["Message"] = message;
                return RedirectToAction(nameof(Index));
        
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);
        
                // 2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "an error has occured during updating the Employee :(";
            }
        
            ModelState.AddModelError(string.Empty, message);
            return View(employeeVM);
        }

        #endregion

        #region Delete

        [HttpPost]  // POST
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var message = string.Empty;

            try
            {
                var deleted = await _employeeService.DeleteEmployeeAsync(id);

                if (deleted)
                    return RedirectToAction(nameof(Index));

                message = "an error has occured during deleting the Employee :(";
            }
            catch (Exception ex)
            {
                // 1. Log Exception
                _logger.LogError(ex, ex.Message);

                // 2. Set Message
                message = _environment.IsDevelopment() ? ex.Message : "an error has occured during deleting the Employee :(";
            }

            //ModelState.AddModelError(string.Empty, message);
            return RedirectToAction(nameof(Index));
        }

        #endregion
    }
}

LinkDev.IKEA.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title> @ViewData["Title"] - IKEA </title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/authLayout.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1> @ViewData["Title"] </h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	@await RenderSectionAsync("ValidationScripts", required: false)
</body>
</html>

LinkDev.IKEA.PL/Views/Shared/_ButtonsPartial.cshtml
@model int
<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal-@Model">
        <i class="fas fa-trash"></i> Delete
    </button>
</td>

LinkDev.IKEA.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IKEA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LinkDev.IKEA.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IKEA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Departments</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employees</a>
                        </li>
                        <div class="dropdown" style="position: absolute; right: 20px;">
                            <button class="btn btn-dark dropdown-toggle" type="button" id="userDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                                @User?.Identity?.Name
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                                <li>
                                    <a class="dropdown-item" asp-controller="Account" asp-action="SignOut">
                                        <i class="fas fa-sign-out-alt"></i> Sign Out
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <script src="~/lib/jquery/dist/jquery.min.js"></script>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - IKEA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScripts", required: false)
</body>
</html>